# Generated by Django 2.1.2 on 2018-10-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=256, null=True)),
                ('trained_date', models.DateTimeField(auto_now=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('accuracy_r2', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_code', models.CharField(max_length=50)),
                ('accom_stars', models.IntegerField(blank=True, null=True)),
                ('staff_pick', models.IntegerField(blank=True, null=True)),
                ('trip_adv_rating', models.IntegerField(blank=True, null=True)),
                ('trip_adv_reviews', models.IntegerField(blank=True, null=True)),
                ('has_swimming_pool', models.IntegerField(blank=True, null=True)),
                ('has_sauna', models.IntegerField(blank=True, null=True)),
                ('has_jacuzzi', models.IntegerField(blank=True, null=True)),
                ('has_tv_in_room', models.IntegerField(blank=True, null=True)),
                ('has_air_conditioning', models.IntegerField(blank=True, null=True)),
                ('has_wifi', models.IntegerField(blank=True, null=True)),
                ('has_hot_tub', models.IntegerField(blank=True, null=True)),
                ('has_lift', models.IntegerField(blank=True, null=True)),
                ('suitable_for_children', models.IntegerField(blank=True, null=True)),
                ('has_child_care', models.IntegerField(blank=True, null=True)),
                ('has_bar', models.IntegerField(blank=True, null=True)),
                ('has_sea_view', models.IntegerField(blank=True, null=True)),
                ('close_to_resort', models.IntegerField(blank=True, null=True)),
                ('close_to_lift', models.IntegerField(blank=True, null=True)),
                ('ski_in_ski_out', models.IntegerField(blank=True, null=True)),
                ('days_booked_before_travel', models.IntegerField(blank=True, null=True)),
                ('holiday_duration', models.IntegerField(blank=True, null=True)),
                ('travel_week', models.IntegerField(blank=True, null=True)),
                ('booking_week', models.IntegerField(blank=True, null=True)),
                ('apartment', models.IntegerField(blank=True, null=True)),
                ('holiday_home', models.IntegerField(blank=True, null=True)),
                ('hotel', models.IntegerField(blank=True, null=True)),
                ('chalet', models.IntegerField(blank=True, null=True)),
                ('bed_and_breakfast', models.IntegerField(blank=True, null=True)),
                ('half_board', models.IntegerField(blank=True, null=True)),
                ('full_board', models.IntegerField(blank=True, null=True)),
                ('all_enclusive', models.IntegerField(blank=True, null=True)),
                ('self_catering', models.IntegerField(blank=True, null=True)),
                ('dep_DUB', models.IntegerField(blank=True, null=True)),
                ('dep_BFS', models.IntegerField(blank=True, null=True)),
                ('dep_BHD', models.IntegerField(blank=True, null=True)),
                ('dep_ORK', models.IntegerField(blank=True, null=True)),
                ('dep_LGW', models.IntegerField(blank=True, null=True)),
                ('dep_MAN', models.IntegerField(blank=True, null=True)),
                ('predicted_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
