version: '3'

services:
  web:
    build:
      context: ../../../
      dockerfile: docker/server/production/Dockerfile
    container_name: price_recommender_server
    volumes:
      - .:/price_recommender_server
    ports:
      - "8000:8000/tcp"
    tty: true