# Generated by Django 2.1.2 on 2018-11-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltraining',
            name='model_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
